"""empty message

Revision ID: 85141194af0a
Revises: 92f909726523
Create Date: 2021-12-08 11:51:41.954016

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '85141194af0a'
down_revision = '92f909726523'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('businesses',
    sa.Column('business_id', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('address', sa.String(), nullable=True),
    sa.Column('city', sa.String(), nullable=True),
    sa.Column('state', sa.String(), nullable=True),
    sa.Column('overall_star', sa.Float(), nullable=True),
    sa.Column('review_count', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('business_id')
    )
    op.create_index(op.f('ix_businesses_business_id'), 'businesses', ['business_id'], unique=False)
    op.drop_index('ix_boba_businesses_business_id', table_name='boba_businesses')
    op.drop_table('boba_businesses')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('boba_businesses',
    sa.Column('business_id', sa.VARCHAR(), nullable=False),
    sa.Column('name', sa.VARCHAR(), nullable=True),
    sa.Column('address', sa.VARCHAR(), nullable=True),
    sa.Column('city', sa.VARCHAR(), nullable=True),
    sa.Column('state', sa.VARCHAR(), nullable=True),
    sa.Column('overall_star', sa.FLOAT(), nullable=True),
    sa.Column('review_count', sa.INTEGER(), nullable=True),
    sa.PrimaryKeyConstraint('business_id')
    )
    op.create_index('ix_boba_businesses_business_id', 'boba_businesses', ['business_id'], unique=False)
    op.drop_index(op.f('ix_businesses_business_id'), table_name='businesses')
    op.drop_table('businesses')
    # ### end Alembic commands ###
