"""empty message

Revision ID: bdb18dd822f4
Revises: 291b923830c0
Create Date: 2021-12-08 11:20:50.300040

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bdb18dd822f4'
down_revision = '291b923830c0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_boston_boba_businesses_business_id'), 'boston_boba_businesses', ['business_id'], unique=False)
    op.create_index(op.f('ix_drink_reviews_business_id'), 'drink_reviews', ['business_id'], unique=False)
    op.create_index(op.f('ix_top_drinks_business_id'), 'top_drinks', ['business_id'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_top_drinks_business_id'), table_name='top_drinks')
    op.drop_index(op.f('ix_drink_reviews_business_id'), table_name='drink_reviews')
    op.drop_index(op.f('ix_boston_boba_businesses_business_id'), table_name='boston_boba_businesses')
    # ### end Alembic commands ###
