NOUNS_TO_EXCLUDE = {
    "tea",
    "teas",
    "our tea",
    "the tea",
    "the teas",
    "their teas",
    "milk tea",
    "milk teas",
    "regular milk tea",
    "amazing milk tea",
    "the amazing milk tea",
    "the milk tea",
    "the milk teas",
    "their milk tea",
    "their milk teas",
    "their bubble tea",
    "bubble tea",
    "bubble teas",
    "bubble milk tea",
    "the bubble tea",
    "the boba tea",
    "best boba tea",
    "boba tea",
    "boba teas",
    "kung fu tea",
    "vivi bubble tea",
    "great bubble tea",
    "his tea",
    "enough tea",
    "some tea",
}