"""empty message

Revision ID: 291b923830c0
Revises: 
Create Date: 2021-12-08 10:55:02.357944

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '291b923830c0'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('boston_boba_businesses',
    sa.Column('business_id', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('address', sa.String(), nullable=True),
    sa.Column('city', sa.String(), nullable=True),
    sa.Column('state', sa.String(), nullable=True),
    sa.Column('overall_star', sa.Float(), nullable=True),
    sa.Column('review_count', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('business_id')
    )
    op.create_table('drink_reviews',
    sa.Column('business_id', sa.String(), nullable=False),
    sa.Column('drink_name', sa.String(), nullable=False),
    sa.Column('date', sa.String(), nullable=True),
    sa.Column('text', sa.String(), nullable=False),
    sa.Column('stars', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('business_id', 'drink_name', 'text')
    )
    op.create_table('top_drinks',
    sa.Column('business_id', sa.String(), nullable=False),
    sa.Column('drink_name', sa.String(), nullable=False),
    sa.Column('score', sa.Float(), nullable=True),
    sa.PrimaryKeyConstraint('business_id', 'drink_name')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('top_drinks')
    op.drop_table('drink_reviews')
    op.drop_table('boston_boba_businesses')
    # ### end Alembic commands ###
