"""add reviews table

Revision ID: 308ec8c1a199
Revises: c7b11f75bed9
Create Date: 2021-12-19 23:39:33.138742

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '308ec8c1a199'
down_revision = 'c7b11f75bed9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('reviews',
    sa.Column('review_id', sa.String(), nullable=False),
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('business_id', sa.String(), nullable=False),
    sa.Column('stars', sa.Integer(), nullable=True),
    sa.Column('useful', sa.Integer(), nullable=True),
    sa.Column('funny', sa.Integer(), nullable=True),
    sa.Column('cool', sa.Integer(), nullable=True),
    sa.Column('text', sa.String(), nullable=True),
    sa.Column('date', sa.String(), nullable=True),
    sa.Column('text_length', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('review_id', 'user_id', 'business_id')
    )
    op.create_index(op.f('ix_reviews_review_id'), 'reviews', ['review_id'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_reviews_review_id'), table_name='reviews')
    op.drop_table('reviews')
    # ### end Alembic commands ###
