"""Create business tables

Revision ID: 5aadc859306b
Revises: 
Create Date: 2021-12-11 21:12:54.427859

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5aadc859306b'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('business',
    sa.Column('business_id', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('address', sa.String(), nullable=True),
    sa.Column('city', sa.String(), nullable=True),
    sa.Column('state', sa.String(), nullable=True),
    sa.Column('overall_star', sa.Float(), nullable=True),
    sa.Column('review_count', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('business_id')
    )
    op.create_index(op.f('ix_business_business_id'), 'business', ['business_id'], unique=False)
    op.create_table('drink_reviews',
    sa.Column('business_id', sa.String(), nullable=False),
    sa.Column('drink_name', sa.String(), nullable=False),
    sa.Column('review_id', sa.String(), nullable=False),
    sa.Column('date', sa.String(), nullable=True),
    sa.Column('text', sa.String(), nullable=True),
    sa.Column('stars', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('business_id', 'drink_name', 'review_id')
    )
    op.create_index(op.f('ix_drink_reviews_business_id'), 'drink_reviews', ['business_id'], unique=False)
    op.create_table('top_drinks',
    sa.Column('business_id', sa.String(), nullable=False),
    sa.Column('drink_name', sa.String(), nullable=False),
    sa.Column('score', sa.Float(), nullable=True),
    sa.PrimaryKeyConstraint('business_id', 'drink_name')
    )
    op.create_index(op.f('ix_top_drinks_business_id'), 'top_drinks', ['business_id'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_top_drinks_business_id'), table_name='top_drinks')
    op.drop_table('top_drinks')
    op.drop_index(op.f('ix_drink_reviews_business_id'), table_name='drink_reviews')
    op.drop_table('drink_reviews')
    op.drop_index(op.f('ix_business_business_id'), table_name='business')
    op.drop_table('business')
    # ### end Alembic commands ###
